//created on: Feb 2, 2015
package rules

//list any import classes here.



//declare any global variables here
rule "Add property negativeControl when sample is imported "
	@nglSQ( sampleCreation )
	dialect "java"
	salience 900
	no-loop
    when
        $sample : Sample($properties:properties, $properties!=null)
        not PropertyValue() from $properties.get("negativeControl")
        $projectCode : String(this in ('CDU','CDW','CDX','CDY','CDZ','CEA','CEB')) from $sample.projectCodes
    then
    	Logger.debug("Add property negative control to : "+$sample.code);  
       	
       	PropertySingleValue psv = new PropertySingleValue(Boolean.TRUE);
       	$sample.properties.put("negativeControl", psv);
	end
	
rule "Add property fishAnatomy when sample is imported or updated "
	@nglSQ( sampleCreation )
	dialect "java"
	salience 900
	no-loop
    when
        $sample : Sample($properties:properties, $properties!=null, typeCode=="fish", $pvTaraProtocol:properties.get("taraProtocol")!=null)
        
        not PropertyValue() from $properties.get("fishAnatomy")
        
    then
    	Logger.debug("Add property fishAnatomy to : "+$sample.code);  
       	String fishAnatomy = $pvTaraProtocol.value.toString();
       	if('GIL'.equals(fishAnatomy))fishAnatomy='GILLS';
       	
       	PropertySingleValue psv = new PropertySingleValue(fishAnatomy);
       	$sample.properties.put("fishAnatomy", psv);
	end	
