#created on: Nov 21, 2013
package rules

#list any import classes here.
import models.laboratory.run.instance.Run;
import models.laboratory.run.instance.Lane;
import models.laboratory.run.instance.Treatment;
import models.laboratory.run.instance.ReadSet;
import models.laboratory.alert.instance.Alert;
import models.utils.InstanceConstants;
import models.laboratory.common.instance.PropertyValue;
import models.laboratory.common.instance.property.PropertySingleValue;
import fr.cea.ig.MongoDBDAO;
import alert.AlertSAVInfo;
import mail.MailServices;
import play.Logger;
import com.typesafe.config.ConfigFactory;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.List;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Arrays;
import java.text.DecimalFormat;
