#created on: Nov 21, 2013
package rules

#declare any global variables here
declare ReadSetInfo
	laneNumber : Integer @key
	nbClusterLane : Long @key
	readSet : ReadSet @key
	validSeqPercent : Double
end

declare LaneInfo
	run : Run
	lane : Lane 
	sizeReadSets : Integer 
	readSets : List 
	nbClusterLane : Long
end

rule "Initialize LaneInfo"
	@nglBI( rg_1 )
	dialect "java"
	salience 500
	no-loop
	when
		$run : Run()
		$lane : Lane($treatment : treatments["ngsrg"], $treatment!=null) from $run.lanes
		$mapValue : Map() from $treatment.results.values()
       	$nbClusterLane : Entry(key == "nbClusterInternalAndIlluminaFilter") from $mapValue.entrySet()
	then
		Logger.debug("Create LaneInfo "+$lane.getNumber());
		LaneInfo laneInfo = new LaneInfo($run, $lane, $lane.getReadSetCodes().size(), new ArrayList(),(Long)((PropertyValue)$nbClusterLane.getValue()).getValue());
		insert(laneInfo);
	
end

rule "Get all readSet"
	@nglBI( rg_1 )
	dialect "java"
	salience 400
	no-loop
    when
        $run : Run( )
       	$lane : Lane( $treatment : treatments["ngsrg"], $treatment!=null) from $run.lanes
       	$readSet : String() from $lane.readSetCodes
       	$laneInfo : LaneInfo(lane==$lane);
    then
    	//Get readSet from database to calculate each validSeqPercent per readSet
    	ReadSet readSet = MongoDBDAO.findByCode(InstanceConstants.READSET_ILLUMINA_COLL_NAME, ReadSet.class, $readSet);	
    	ReadSetInfo readSetInfo = new ReadSetInfo($lane.getNumber(),$laneInfo.getNbClusterLane(),readSet);
    	//Update laneInfo
    	$laneInfo.getReadSets().add(readSetInfo);
    	insert(readSetInfo);
    	update($laneInfo);
end


rule "Calculate seqPercent readSet"
	@nglBI( rg_1 )
	dialect "java"
	salience 300
	no-loop
	when
		$readSetInfo : ReadSetInfo($treatment : readSet.treatments["ngsrg"], $treatment!=null, validSeqPercent==null)
		$mapValue : Map() from $treatment.results.values()
		$nbCluster : Entry(key=="nbCluster") from $mapValue.entrySet()
	then
		//Calculate validSeqPercent
		Long nbClusterReadSet = ((Long)((PropertyValue)$nbCluster.getValue()).getValue());
		Long nbClusterLane = $readSetInfo.getNbClusterLane();
		Double validSeqPercent = roundValue((double)nbClusterReadSet/nbClusterLane*100);
		//Create new PropertyValue
		PropertySingleValue propertyValidSeqPercent = new PropertySingleValue(validSeqPercent);
		$mapValue.put("validSeqPercent", propertyValidSeqPercent);
		//Update ReadSet in database
		MongoDBDAO.save(InstanceConstants.READSET_ILLUMINA_COLL_NAME, $readSetInfo.getReadSet());
		$readSetInfo.setValidSeqPercent(validSeqPercent);
		update($readSetInfo);
end

rule "Calculate seqLossPercent Lane"
	@nglBI( rg_1 )
	dialect "java"
	salience 200
	no-loop
	when
		$laneInfo : LaneInfo(sizeReadSets == readSets.size(), $treatment : lane.treatments["ngsrg"], $treatment!=null)
		$mapValue : Map() from $treatment.results.values()
		$sumValidSeqPercent : Double() from accumulate (ReadSetInfo(laneNumber==$laneInfo.lane.number, validSeqPercent!=null, $value : validSeqPercent), sum($value))
	then
		Double seqLossPercent =roundValue(100-$sumValidSeqPercent);
		//Create new PropertyValue seqLossPercent
		PropertySingleValue propertySeqLossPercent = new PropertySingleValue(seqLossPercent);
		$mapValue.put("seqLossPercent", propertySeqLossPercent);
		//Update Lane via run
		MongoDBDAO.save(InstanceConstants.RUN_ILLUMINA_COLL_NAME, $laneInfo.getRun());
end

function Double roundValue(double value)
{
	DecimalFormat df=new DecimalFormat("0.00");
	return (Double)df.parse(df.format(value)).doubleValue();
}