//created on: Aug 6, 2014
//Rules for validation
package rules

declare LaneInfo
	position : String
	contentInfos : List 
end

declare ContentInfo
	position : String
	containerCode : String 
	tag : String 
	tagCategory : String 
	sampleCode : String
	tagRealSize : Integer
	sequence : String
end

rule "Debug validations"
	@nglSQ( validations )
	dialect "java"
	salience 1000
	no-loop
    when
	eval(true)
    then
		Logger.debug("Rules annotation @nglSQ(validations)");    
	end

rule "Init object LaneInfo in WM"
	@nglSQ( validations )
	dialect "java"
	salience 700
	no-loop
    when
    $atomicTransfert: AtomicTransfertMethod($position : line)
    not LaneInfo($position==position)
    then
    
    LaneInfo laneInfo = new LaneInfo($position,new ArrayList());
    Logger.debug("Lane Info Position :"+$position);
    insert(laneInfo);
    
	end



rule "Init objects ContentInfo in WM"
		@nglSQ( validations )
	dialect "java"
	salience 600
	no-loop
    when
    $atomicTransfert: AtomicTransfertMethod($position:line,$inputContainers : inputContainerUseds, $inputContainers.size()!=0)
	$container : ContainerUsed( $contents : contents,$contents!=null) from $inputContainers
	$content : Content() from $contents	 
	$laneInfo : LaneInfo($position==position)
    then
   
    String tag="VIDE";
    String tagCategory="VIDE";
    Integer tagRealSize = 0;
    String sequence = "VIDE";
    if($content.properties.containsKey("tag")){
    	tag=$content.properties.get("tag").value.toString();
    	Index index=MongoDBDAO.findOne(InstanceConstants.PARAMETER_COLL_NAME, Index.class, DBQuery.is("typeCode", "index-illumina-sequencing").is("code", tag));
    	if(index != null){
    		sequence = index.sequence;
    		tagRealSize = index.sequence.length();
    	}else{
    		Logger.debug("Can't find index "+tag+" in collection "+InstanceConstants.PARAMETER_COLL_NAME);
    	}
    }
    if($content.properties.containsKey("tagCategory")) tagCategory=$content.properties.get("tagCategory").value.toString();

	ContentInfo contentInfo= new ContentInfo($atomicTransfert.line,$container.code,tag,tagCategory,$content.sampleCode, tagRealSize, sequence);
	Logger.debug("Content Info Position : "+$atomicTransfert.line+ ", Sample Code :"+$content.sampleCode + ", Container Code :"+$container.code+", Tag :"+tag+", tagCategory :"+tagCategory+", size :"+tagRealSize+", sequence :"+sequence);
    $laneInfo.getContentInfos().add(contentInfo);
	insert(contentInfo);
	
    end



rule "Input not null for Experiment Type Prepa-flowcell"
	@nglSQ( validations )
	dialect "java"
	salience 510
	no-loop
    when
    	$experiment:Experiment($typeCode : typeCode, $typeCode=="prepa-flowcell")
    	$atomics:AtomicTransfertMethod($inputContainers : inputContainerUseds)
    	$contextValidation:ContextValidation()
    	eval($inputContainers.size()==0)
    then
    	//Logger.debug("Erreur position "+$atomics.position);
    	$contextValidation.addErrors("lane["+$atomics.line+"]",	"error.validationexp.emptyoutputcontainer",$atomics.line);
    end
    
    
rule "Container duplicate in Lane"
	@nglSQ( validations )
	dialect "java"
	salience 500
	no-loop
    when
    	  LaneInfo($position:position)
    	  AtomicTransfertMethod($position==line,$inputContainers : inputContainerUseds)
    	  $containerCodes : Set(empty==false, size >= 1) from accumulate( ContainerUsed($containerCode:code) from $inputContainers,
	                         init( HashSet result = new HashSet(); HashSet containers=new HashSet(); ),
                              action( if(!containers.contains($containerCode)){ containers.add($containerCode); } 
                              				else if(!result.contains($containerCode)) { result.add($containerCode);} ),
                             reverse( result.remove($containerCode); ),
                              result( result) )
		 $containerDuplicate : String() from $containerCodes
		 $contextValidation:ContextValidation()
    then
    	//Logger.debug("Erreur containers "+$containerDuplicate);
 		$contextValidation.addErrors("lane["+$position+"]",	"error.validationexp.duplicateinputcontainers",$containerDuplicate, $position);
    end
   	
rule "Sum % percentage per piste = 100 % "
	@nglSQ( validations )
	dialect "java"
	salience 580
	no-loop
    when
    $atomics:AtomicTransfertMethod($inputContainers : inputContainerUseds)
    Experiment($instrument: instrument)   
    $total : Double() from accumulate(ContainerUsed( $n:percentage, percentage!=null) from $inputContainers, sum( $n ) )
    $container: ContainerUsed($cat : categoryCode) from $inputContainers
    eval(!($total>=99.9 && $total<=100) )
    $contextValidation:ContextValidation()
   	 then
   		Logger.debug("Regles de validation des pourcentages solexa "+ $total +' '+$atomics.line);   		
   		
   		if(("tube").equals($instrument.outContainerSupportCategoryCode)){   			 
   			if(!$contextValidation.errors.containsKey("tube["+$atomics.line+"]")){  		
   			$contextValidation.addErrors("tube["+$atomics.line+"]",	"error.validationexp.percentperoutputcontainertube", $total,$atomics.line);
   			}
   		}else if(Pattern.matches("^flowcell.*",$instrument.outContainerSupportCategoryCode)){
   			$contextValidation.addErrors("lane["+$atomics.line+"]",	"error.validationexp.percentperoutputcontainerlane", $total,$atomics.line);
   		}else if(("mapcard").equals($instrument.outContainerSupportCategoryCode)){
   			if(!$contextValidation.errors.containsKey("mapcard["+$atomics.line+"]")){
   			$contextValidation.addErrors("mapcard["+$atomics.line+"]",	"error.validationexp.percentperoutputcontainermapcard", $total,$atomics.line);
   			}
   		}else{
   			if(!$contextValidation.errors.containsKey("output container["+$atomics.line+"]")){
   			$contextValidation.addErrors("output container["+$atomics.line+"]",	"error.validationexp.percentperoutputcontainerdefault", $total);
   			}
   		}   	
   		
   	end
   	
rule "Tag identique sur la meme position"
	@nglSQ (validations )
	dialect "java"
	salience 400
	no-loop
    when
    	   $contentInfo1 : ContentInfo($tag :tag,$sampleCode :sampleCode,$position:position,$containerCode1:containerCode)
           $contentInfo2 : ContentInfo(this != $contentInfo1, tag == $tag, position==$position, sampleCode!=$sampleCode,$containerCode2:containerCode)
           $contextValidation:ContextValidation()
    then
    	Logger.debug("Tag error "+$contentInfo1 + " position "+$position);
    	$contextValidation.addErrors("lane["+$position+"]",	"error.validationexp.sametag", $tag,$containerCode1,$containerCode2);    	
    end

rule "Many TagCategory on same position"
	@nglSQ (validations )
	dialect "java"
	salience 300
	no-loop
when
	 LaneInfo($position:position)
     $tagCategories : Set(empty==false, size > 1) from accumulate( ContentInfo ( $tagCategory : tagCategory,$position==position),
                        collectSet( $tagCategory) )
	  $contextValidation:ContextValidation($errors : errors)
then
	Logger.debug("TagCategory error "+ $tagCategories.size()+" position "+$position);
    $contextValidation.addErrors("lane["+$position+"]",	"error.validationexp.manytagCategory", $position);
end

rule "Same tag size"
	@nglSQ (validations )
	dialect "java"
	salience 301
	no-loop
when
	 LaneInfo($position:position)
     $tagRealSizes : Set(empty==false, size > 1) from accumulate( ContentInfo ( $tagRealSize : tagRealSize, $position==position),
                        collectSet( $tagRealSize) )
	  $contextValidation:ContextValidation($errors : errors)
then
	Logger.debug("Tag squence error "+ $tagRealSizes+" position "+$position);
    $contextValidation.addErrors("lane["+$position+"]",	"error.validationexp.manytagSize", $position);
end

rule "Same sequence"
	@nglSQ (validations )
	dialect "java"
	salience 302
	no-loop
when
	 LaneInfo($position:position, $contentInfos:contentInfos)
     $sequences : Set(empty==false, size != $contentInfos.size()) from accumulate( ContentInfo ( $sequence : sequence, $position==position),
                        collectSet( $sequence) )
	  $contextValidation:ContextValidation($errors : errors)
then
	Logger.debug("Tag squence error "+ $sequences+" and "+$contentInfos.size()+" position "+$position);
    $contextValidation.addErrors("lane["+$position+"]",	"error.validationexp.sameTagSequence", $position, $sequences);
end

rule "RunStartDate propertie is mandatory to create Illumina Depot and Opgen Depot"
@nglSQ (validations )
	dialect "java"
	salience 500
	no-loop
when
	$experiment: Experiment($typeCode:typeCode,$typeCode=="illumina-depot"|| $typeCode=="opgen-depot" || $typeCode=="nanopore-depot" , $state: state, $state.code=="N",$experimentProperties: experimentProperties, traceInformation!=null, $creationDate: traceInformation.creationDate)
	not (Entry(key == "runStartDate") from $experimentProperties.entrySet())
then	
	Logger.info("Règle RunStartDate propertie OK");
	PropertySingleValue value = new PropertySingleValue($creationDate);
	if($experimentProperties==null){$experimentProperties = new HashMap<String,PropertyValue>();}
	$experimentProperties.remove("runStartDate");
	$experimentProperties.put("runStartDate", value);
	//$contextValidation.addErrors("experiment", "error.validationexp.mandatoryrunstartdate", $typeCode, $runStartDate);
	Logger.info("Date réel de dépot = " + $experimentProperties.get("runStartDate"));
	update ($experiment);

end









    