#created on: Jul 7, 2014
package birds

rule "Define variable lineParmeter for createReleaseXML specification"
	@BirdsRule(ExecutionService)
	dialect 'java'
	salience 300
	no-loop
    when
       $executionService : ExecutionService( status == ExecutionService.PRE_JOB_EXECUTION_STATUS)
       $job : Job( treatmentSpecification!=null, treatmentSpecification.name == "createReleaseXML", treatmentSpecification.project.name == "SRA" )
    then
       Logger log = Logger.getLogger("ngl.sub.rules");
       log.debug("Set code in url for spec createReleaseXML");
       $job.setUnixCommand($job.getUnixCommand().replace("%code%", $job.getUniqueJobResource("releaseToXML").getProperty("code")));
       log.debug("Unix command "+$job.getUnixCommand());
       log.debug("Code "+$job.getUniqueJobResource("releaseToXML").getProperty("code"));
end

rule "add releaseXML resources in internalRefReleaseXML to fire sendReleaseXML"
	@BirdsRule( addResources ) 
	dialect 'java'
	salience 200
	when
		$flag : Flag ( done == false ) 
		$output : OutputSpecificationElement(treatmentSpecification.name == "createReleaseXML")
	  	$referential : ResourcesReferential ( name == "internalRefReleaseXML" )
		$resourceSet : ResourceSet( ioSpecificationElement == $output )
		$job : Job(treatmentSpecification!=null, treatmentSpecification.name == "createReleaseXML")
	then
		Logger log = Logger.getLogger("ngl.sub.rules");
		log.debug("Add resources rules for sendReleaseXML from file "+$job.getProperty(Job.STDOUT));
		Set<ResourceProperties> setResources = new JSONDevice().parseJSONFromFileName($job.getProperty(Job.STDOUT));
		for(ResourceProperties rp : setResources){
			JobResource outputResource = $resourceSet.createJobResource($output.getResourceType(),$referential.getName());
	   		outputResource.setResourceProperties(rp);
		}
		$flag.setDone(true);
		modify($flag){};
		modify($resourceSet){};
end
