#created on: Jul 7, 2014
package birds

import fr.cea.ig.auto.submission.SRAFilesUtil;

#règle mise à jour la valeur du parametre localDirectoryPath selon resource en entrée
rule "update localDirectoryPath parameter"
	@BirdsRule(fsRule)
	dialect 'java'
	salience 300
	no-loop
		when
			$treatSpec : TreatmentSpecification(name=="transfertRawData", project.name=="SRA")
			$job : Job()
		then
			Logger log = Logger.getLogger("ngl.sub.rules");
			log.debug("set parameter value");
			//Get input resource
			String valueLocalDirPath = $job.getUniqueJobResource("rawDataDir").getProperty("submissionDirectory");
			log.debug("set value local dir path to "+valueLocalDirPath);
			#Add extension in localDirectoryPath
			#$job.setParameterValue("localDirectoryPath",valueLocalDirPath+"/*.fastq.gz "+valueLocalDirPath+"/*.sff "+valueLocalDirPath+"/*.srf");
			String[] extensions = new String[] { "fastq.gz", "sff" , "srf" };
			$job.setParameterValue("localDirectoryPath",SRAFilesUtil.getLocalDirectoryParameter(valueLocalDirPath,extensions));
end

#Règle organisation syntaxe FTP selon ticket NGL-164
#ncftpput -u login -p passWord -R -t 60 -V remoteHost remotePath localDirectoryPath
rule "unix syntax ncftpput for EBI"
	@BirdsRule(unixSyntaxRule)
	dialect 'java'
	salience 300
	no-loop
		when
			$strategy : UnixCommandSyntaxStrategy ( name == "ncftpputSyntax" , commandLine == null)
		then
			Logger log = Logger.getLogger("ngl.sub.rules");	    
			//Organize order parameterLine
			String parameterLine = $strategy.getParameterValue().get("userEBI") + " " + 
									$strategy.getParameterValue().get("pwdEBI") + " " +
									$strategy.getParameterValue().get("recursif") + " " +
									$strategy.getParameterValue().get("timeOut") + " " +
									$strategy.getParameterValue().get("remoteHost") + " " +
									$strategy.getParameterValue().get("remotePath") + " " +	
									$strategy.getParameterValue().get("localDirectoryPath");
			$strategy.setCommandLine($strategy.getExecutableName() + " " + parameterLine);
			log.debug("command line : " + $strategy.getCommandLine());
		
			modify($strategy) {}
end

