#created on: Jul 7, 2014
package birds

import fr.cea.ig.auto.submission.SRAFilesUtil;

#règle mise à jour la valeur du parametre fileList selon resource en entrée et creation fichier WGS
rule "update localDirectoryPath parameter"
	@BirdsRule(fsRule)
	dialect 'java'
	salience 300
	no-loop
		when
			$treatSpec : TreatmentSpecification(name=="transfertRawData", project.name=="SRA")
			$job : Job()
		then
			Logger log = Logger.getLogger("ngl.sub.rules");
			log.debug("Get rawData");
			//Get rawData
			JSONDevice jsonDevice = new JSONDevice();
			Set<ResourceProperties> rps = jsonDevice.httpGetJSON(ProjectProperties.getProperty("server")+"/submissions/"+$job.getUniqueJobResource("rawDataDir").getProperty("code")+"/experiments/rawDatas");
			log.debug("Size of rawData : "+rps.size());
			String directoryPath = $job.getUniqueJobResource("rawDataDir").getProperty("submissionDirectory");
			String filePath = $job.getParameterValue("fileList").getValue().replace("%directoryPath%",directoryPath);
			SRAFilesUtil.createWGSFile(filePath, rps);
			log.debug("set parameter value");
			//Get input resource
			$job.setParameterValue("fileList", filePath);
end

#Règle organisation syntaxe Aspera selon ticket NGL-334
#/env/cns/opt/aspera/bin/ascp -T -k2 -Q -m 300M -v 
#		--file-list=/env/cns/submit_traces/SRA/SNTS_output_xml/AHX/list_aspera_WGS 
#		--mode send --host fasp.ega.ebi.ac.uk --user era-drop-9 / | tee result
rule "unix syntax ncftpput for EBI"
	@BirdsRule(unixSyntaxRule)
	dialect 'java'
	salience 300
	no-loop
		when
			$strategy : UnixCommandSyntaxStrategy ( name == "ncftpputSyntax" , commandLine == null)
		then
			Logger log = Logger.getLogger("ngl.sub.rules");	    
			//Organize order parameterLine
			String parameterLine = $strategy.getParameterValue().get("encryption") + " " + 
									$strategy.getParameterValue().get("partialTransfert") + " " +
									$strategy.getParameterValue().get("optionQ") + " " +
									$strategy.getParameterValue().get("optionM") + " " +
									$strategy.getParameterValue().get("optionV") + " " +
									$strategy.getParameterValue().get("fileList") + " " +	
									$strategy.getParameterValue().get("mode") + " "+
									$strategy.getParameterValue().get("hostName") + " "+
									$strategy.getParameterValue().get("userEBI") + " "+
									$strategy.getParameterValue().get("localDirectory");
			$strategy.setCommandLine($strategy.getExecutableName() + " " + parameterLine + " | tee result");
			log.debug("command line : " + $strategy.getCommandLine());
			modify($strategy) {}
end

