//created on: Aug 6, 2014
//Rules for validation
package rules



rule "Input not null for all Experiment"
	@nglSQ( validations )
	dialect "java"
	salience 510
	no-loop
    when
    	$experiment:Experiment()
    	$atomics:AtomicTransfertMethod($inputContainers : inputContainerUseds)
    	$contextValidation:ContextValidation()
    	eval($inputContainers.size()==0)
    then
    	//Logger.debug("Erreur position "+$atomics.position);
    	$contextValidation.addErrors("lane["+$atomics.line+"]",	"error.validationexp.emptyoutputcontainer",$atomics.line);
    end
    

rule "Set RunStartDate to Illumina Depot, Opgen Depot, Nanopore Depot if not exist"
@nglSQ (calculations )
	dialect "java"
	salience 500
	no-loop
when
	$experiment: Experiment($typeCode:typeCode,$typeCode=="illumina-depot"|| $typeCode=="opgen-depot" || $typeCode=="nanopore-depot" || $typeCode=="bionano-depot" , $state: state, $state.code=="N", 
					$experimentProperties: experimentProperties, (null == $experimentProperties || (null != $experimentProperties && null == $experimentProperties.get("runStartDate"))), traceInformation!=null, $creationDate: traceInformation.creationDate)	
then	
	Logger.info("Regle RunStartDate propertie OK");
	if($experimentProperties==null){
		$experiment.experimentProperties=new HashMap<String,PropertyValue>();
	}
	PropertySingleValue value = new PropertySingleValue($creationDate);
	$experiment.experimentProperties.put("runStartDate", value);
	//$contextValidation.addErrors("experiment", "error.validationexp.mandatoryrunstartdate", $typeCode, $runStartDate);
	Logger.info("Date reel de dépot = " + $experiment.experimentProperties.get("runStartDate"));
	update ($experiment);

end









    