#created on: Aug 6, 2014
package rules

import play.Logger;
import java.util.Map;
import models.laboratory.experiment.instance.Experiment;
import models.laboratory.experiment.instance.AtomicTransfertMethod;
import validation.ContextValidation;
import play.data.validation.ValidationError;
import models.laboratory.experiment.instance.ManytoOneContainer;
import models.laboratory.experiment.instance.ContainerUsed;
import models.laboratory.common.instance.PropertyValue;
import models.laboratory.common.instance.property.PropertySingleValue;
import models.laboratory.container.instance.Content;

