#created on: Aug 6, 2014
package rules

import play.Logger;
import java.util.Map;
import models.laboratory.experiment.instance.Experiment;
import models.laboratory.experiment.instance.AtomicTransfertMethod;
import models.laboratory.processes.instance.Process;
import models.laboratory.container.instance.Container;
import validation.ContextValidation;
import play.data.validation.ValidationError;
import models.laboratory.experiment.instance.ManytoOneContainer;
import models.laboratory.experiment.instance.ContainerUsed;
import models.laboratory.common.instance.PropertyValue;
import models.laboratory.common.instance.property.PropertySingleValue;
import models.laboratory.container.instance.Content;
import java.util.*;
import java.math.BigDecimal;
import java.math.RoundingMode;
import models.utils.InstanceConstants;
import fr.cea.ig.MongoDBDAO;
import org.mongojack.DBQuery;
import org.mongojack.DBUpdate;

