#created on: Aug 6, 2014
#Rules for validation
package rules

declare LaneInfo
	position : Integer
	contentInfos : List 
end

declare ContentInfo
	position : Integer
	containerCode : String 
	tag : String 
	tagCategory : String 
	sampleCode : String
end


rule "Init object LaneInfo in WM"
	@nglSQ( validations )
	dialect "java"
	salience 700
	no-loop
    when
    $atomicTransfert: AtomicTransfertMethod($position : position)
    not LaneInfo($position==position)
    then
    
    LaneInfo laneInfo = new LaneInfo($position,new ArrayList());
    Logger.debug("Lane Info Position :"+$position);
    insert(laneInfo);
    
	end


rule "Init objects ContentInfo in WM"
		@nglSQ( validations )
	dialect "java"
	salience 600
	no-loop
    when
    $atomicTransfert: AtomicTransfertMethod($position:position,$inputContainers : getInputContainers(), $inputContainers.size()!=0)
	$container : ContainerUsed( $contents : contents,$contents!=null) from $atomicTransfert.inputContainers
	$content : Content() from $contents	 
	$laneInfo : LaneInfo($position==position)
    then
   
    String tag="VIDE";
    String tagCategory="VIDE";
    if( $content.properties.containsKey("tag")) tag=$content.properties.get("tag").value.toString();
    if( $content.properties.containsKey("tagCategory")) tagCategory=$content.properties.get("tagCategory").value.toString();

	ContentInfo contentInfo= new ContentInfo($atomicTransfert.position,$container.code,tag,tagCategory,$content.sampleCode);
	Logger.debug("Content Info Position : "+$atomicTransfert.position+ ", Sample Code :"+$content.sampleCode + ", Container Code :"+$container.code+", Tag :"+tag+", tagCategory :"+tagCategory);
    $laneInfo.getContentInfos().add(contentInfo);
	insert(contentInfo);
	
    end



rule "Input not null for Experiment Type Prepa-flowcell"
	@nglSQ( validations )
	dialect "java"
	salience 510
	no-loop
    when
    	$experiment:Experiment($typeCode : typeCode, $typeCode=="prepa-flowcell")
    	$atomics:AtomicTransfertMethod($inputContainers : getInputContainers())
    	$contextValidation:ContextValidation()
    	eval($inputContainers.size()==0)
    then
    	//Logger.debug("Erreur position "+$atomics.position);
    	$contextValidation.addErrors("lane["+$atomics.position+"]",	"error.validationexp.emptyoutputcontainer",$atomics.position);
    end
    
    
rule "Container duplicate in Lane"
	@nglSQ( validations )
	dialect "java"
	salience 500
	no-loop
    when
    	  LaneInfo($position:position)
    	  AtomicTransfertMethod($position==position,$inputContainers : getInputContainers())
    	  $containerCodes : Set(empty==false, size >= 1) from accumulate( ContainerUsed($containerCode:code) from $inputContainers,
	                         init( HashSet result = new HashSet(); HashSet containers=new HashSet(); ),
                              action( if(!containers.contains($containerCode)){ containers.add($containerCode); } 
                              				else if(!result.contains($containerCode)) { result.add($containerCode);} ),
                             reverse( result.remove($containerCode); ),
                              result( result) )
		 $containerDuplicate : String() from $containerCodes
		 $contextValidation:ContextValidation()
    then
    	//Logger.debug("Erreur containers "+$containerDuplicate);
 		$contextValidation.addErrors("lane["+$position+"]",	"error.validationexp.duplicateinputcontainers",$containerDuplicate, $position);
    end


rule "Sum % percentage per piste = 100 % "
	@nglSQ( validations )
	dialect "java"
	salience 580
	no-loop
    when
    $atomics:AtomicTransfertMethod($inputContainers : getInputContainers())
    $total : Double() from accumulate( ContainerUsed($n:percentage, percentage!=null) from $inputContainers, sum( $n ) )
    eval($total!=100 && $total!=0)
    $contextValidation:ContextValidation()
   	then
   		//Logger.debug("Regles de validation solexa "+$total +' '+$atomics.position);
   		$contextValidation.addErrors("lane["+$atomics.position+"]",	"error.validationexp.percentperoutputcontainer", $total,$atomics.position);
   	end
   	

   	
rule "Tag identique sur la meme position"
	@nglSQ (validations )
	dialect "java"
	salience 400
	no-loop
    when
    	   $contentInfo1 : ContentInfo($tag :tag,$sampleCode :sampleCode,$position:position,$containerCode1:containerCode)
           $contentInfo2 : ContentInfo(this != $contentInfo1, tag == $tag, position==$position, sampleCode!=$sampleCode,$containerCode2:containerCode)
           $contextValidation:ContextValidation()
    then
    	//Logger.debug("Tag error "+$contentInfo1 + " position "+$position);
    	$contextValidation.addErrors("lane["+$position+"]",	"error.validationexp.sametag", $tag,$containerCode1,$containerCode2);    	
    end

rule "Many TagCategory on same position"
	@nglSQ (validations )
	dialect "java"
	salience 300
	no-loop
when
	 LaneInfo($position:position)
     $tagCategories : Set(empty==false, size > 1) from accumulate( ContentInfo ( $tagCategory : tagCategory,$position==position),
                        collectSet( $tagCategory) )
	  $contextValidation:ContextValidation($errors : errors)
then
	Logger.debug("TagCategory error "+ $tagCategories.size()+" position "+$position);
    $contextValidation.addErrors("lane["+$position+"]",	"error.validationexp.manytagCategory", $position);
end